[package]
name = "postcodes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
geojson = "0.24.1"
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
zstd = "0.13.1"
